### ISSUE TITLE
We should export SpanKind info

### ISSUE THREAD

**Issue by AndrewAXue** [GoogleCloudPlatform/opentelemetry-operations-python#10]
OpenTelemetry is correctly extracting SpanKind information, but our exporter is not exporting it to Cloud Trace.

**Comment by kintel** [comment]
This is blocked on the next release of https://pypi.org/project/google-cloud-trace/ (currently at 0.23.0)

**Comment by AndrewAXue** [comment]
Resolved in this PR https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/58/files
