### ISSUE TITLE
Filter out health check request in grpc

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/opentelemetry-operations-python#110]
As of 0.18b1, [`opentelemetry-instrumentation-grpc`](https://pypi.org/project/opentelemetry-instrumentation-grpc/) doesn't have the feature to exclude trace propagation to the specific endpoints. Because of this, gRPC servers always send health check request traces to Cloud Traces via the exporter as you see in the screenshot below:
![Screenshot from 2021-03-15 16-32-51](https://user-images.githubusercontent.com/145104/111118552-47c69d80-85ac-11eb-8c2a-324c6b5dc730.png)

It would be nice if the exporter support filter option to avoid sending unnecessary traces to the Cloud Trace. Otherwise, the upstream (`opentelemetry-instrumentation-grpc`) should have something similar to `OTEL_PYTHON_FLASK_EXCLUDED_URLS` in [`opentelemetry-instrumentation-flask`](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask)

**Comment by aabmass** [comment]
I think should be done in the instrumentation so other exporters can take advantage.

As a workaround, you could make your own span processor that subclasses or wraps [`BatchSpanProcessor`](https://github.com/open-telemetry/opentelemetry-python/blob/724c7920e71c7cce77cc331ee24659c30d42526c/opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py#L115) to drop spans you're not interested in.

**Comment by aabmass** [comment]
@ymotongpoo do you mind re-opening this issue over here https://github.com/open-telemetry/opentelemetry-python-contrib/issues?

**Comment by ymotongpoo** [comment]
Thank you Aaron for reviewing the issue! I filed this issue in the upstream. Closing this issue here accordingly.

https://github.com/open-telemetry/opentelemetry-python-contrib/issues/373
