### ISSUE TITLE
The spans do not appear under one trace as we expect in "Google Cloud Trace"

### ISSUE THREAD

**Issue by OmarEltamasehy** [GoogleCloudPlatform/opentelemetry-operations-python#131]
Opentelemetry Dependencies

```
opentelemetry-api==0.17b0
opentelemetry-sdk==0.17b0
opentelemetry-instrumentation==0.17b0
opentelemetry-instrumentation-redis==0.17b0
opentelemetry-instrumentation-requests==0.17b0
opentelemetry-instrumentation-django==0.17b0
opentelemetry-instrumentation-psycopg2==0.17b0
opentelemetry-instrumentation-grpc==0.17b0
opentelemetry-exporter-google-cloud==0.17b0
opentelemetry-tools-google-cloud==0.17b0

```
In settings.py

```
from opentelemetry.instrumentation.requests import RequestsInstrumentor
from opentelemetry.instrumentation.psycopg2 import Psycopg2Instrumentor
from opentelemetry.instrumentation.grpc import GrpcInstrumentorServer
# for using redis
from opentelemetry.instrumentation.redis import RedisInstrumentor
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry import trace

# For usig cloudTracing
from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter
from opentelemetry.sdk.trace.export import BatchExportSpanProcessor

# For propagator
from opentelemetry.propagators import set_global_textmap
from opentelemetry.tools.cloud_trace_propagator import (
    CloudTraceFormatPropagator,
)



trace.set_tracer_provider(TracerProvider())
tracer = trace.get_tracer(__name__)

# Create CloudTraceSpanExporter >> for cloud trace
cloud_trace_exporter = CloudTraceSpanExporter()
# Create a BatchExportSpanProcessor and add the exporter to it
span_processor = BatchExportSpanProcessor(cloud_trace_exporter)
# add to the tracer >> cloud trace
trace.get_tracer_provider().add_span_processor(span_processor)

RequestsInstrumentor().instrument()
RedisInstrumentor().instrument()
Psycopg2Instrumentor().instrument()
GrpcInstrumentorServer().instrument()
# Using the X-Cloud-Trace-Context header
set_global_textmap(CloudTraceFormatPropagator())

```

In wsgi.py 
```
from opentelemetry.instrumentation.django import DjangoInstrumentor
DjangoInstrumentor().instrument()
```
As per the above code we expect that the spans appear under one trace for one request but unfortunately the spans appeared as separated spans with separated trace so please help me to show them under one trace.

**Comment by aabmass** [comment]
> As per the above code we expect that the spans appear under one trace for one request but unfortunately the spans appeared as separated spans with separated trace so please help me to show them under one trace.

@OmarEltamasehy this sounds like a propagation issue, can you share some more details: 
- Who is making requests to this service?
- Where are you running this code, local or in GCP somewhere? Are you using `./manage.py` or gunicorn?
- Which spans didn't appear in the same trace? Spans from the same Django app, spans from the caller, or spans from child services?

If you are using Gunicorn or similar, I'd also recommend reading through [this document](https://opentelemetry-python.readthedocs.io/en/latest/examples/fork-process-model/README.html?highlight=gunicorn).

**Comment by aabmass** [comment]
I'm gonna close this issue, but let me know if you are still having issues.

**Comment by ezemegwara** [comment]
i have this issue. i have done everything. my app is in App engine. i just want to trace App engine startup time

**Comment by nabla-c0d3** [comment]
@ezemegwara I posted a workaround in https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/155
