### ISSUE TITLE
Cannot install google opentelemetry

### ISSUE THREAD

**Issue by salberin** [GoogleCloudPlatform/opentelemetry-operations-python#133]
Due to dependency problems, it is currently not possible to install Cloud Trace for opentelemetry. I receive the following error during installation:
```
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
ERROR: opentelemetry-exporter-google-cloud 0.18b0 has requirement opentelemetry-api==0.17b0, but you'll have opentelemetry-api 1.1.0 which is incompatible.
ERROR: opentelemetry-exporter-google-cloud 0.18b0 has requirement opentelemetry-sdk==0.17b0, but you'll have opentelemetry-sdk 1.1.0 which is incompatible.`
```
Any advice would be appreciated

**Comment by aabmass** [comment]
@salberin that version is incompatible with opentelemetry 1.x.

I just released new packages yesterday that work with current version of OpenTelemetry (and going forward). I am working on updating the docs/readmes everywhere with these new package names. Going forward, the packages you should use are:
- Trace exporter (rc) – https://pypi.org/project/opentelemetry-exporter-gcp-trace/
- Trace propagator (rc) – https://pypi.org/project/opentelemetry-propagator-gcp/
- Monitoring exporter (alpha, OTel metrics are in flux) – https://pypi.org/project/opentelemetry-exporter-gcp-monitoring/
- Resource detector (alpha, need to do more testing) – https://pypi.org/project/opentelemetry-resourcedetector-gcp/

Any other GCP OTel packages on PyPI can be ignored going forward and I will update old packages to say so on PyPI with pointers to the new packages. Sorry for the confusion!

**Comment by aabmass** [comment]
@salberin I'm going to close, let me know if you have any other questions
