### ISSUE TITLE
Wrong imports on documentation

### ISSUE THREAD

**Issue by acarnage** [GoogleCloudPlatform/opentelemetry-operations-python#160]
Hello,

I am not sure if this is the right place to post this but I found imports errors while trying the examples.

On this [page](https://google-cloud-opentelemetry.readthedocs.io/en/latest/examples/cloud_trace_propagator/README.html), for both client and server examples:

`from opentelemetry.ext.flask import FlaskInstrumentor` **->** `from opentelemetry.instrumentation.flask import FlaskInstrumentor`

`from opentelemetry.tools.cloud_trace_propagator import [...]`  **->**  `from opentelemetry.propagators.cloud_trace_propagator import [...]`

`import opentelemetry.ext.requests` **->** `from opentelemetry.instrumentation.requests import RequestsInstrumentor`

(I found the proper imports base on this [page](https://google-cloud-opentelemetry.readthedocs.io/en/latest/examples/flask_e2e/README.html))

**Comment by aabmass** [comment]
Thanks for pointing these out, I thought I had fixed them all! PRs are always welcome if you have the time 😄

**Comment by Patil2099** [comment]
I would love to pick this up.
