### ISSUE TITLE
DefaultCredentialsError

### ISSUE THREAD

**Issue by nurhun** [GoogleCloudPlatform/opentelemetry-operations-python#163]
Guys,

However I'm running my django app on GKE, and injecting the project_id to  the CloudTraceSpanExporter but it fails with below error. 

google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started.

Any ideas to skip this without having to set credentials as all parts runs on GCP ?

**Comment by aabmass** [comment]
@nurhun can you provide some more details on your setup

- Are you successfully using any other GCP client libraries in your application or cluster?
- Can you share the setup code for OpenTelemetry?
- Can you share an anonymized k8s yaml?
- Are you using a GKE autopilot cluster by any chance?

This should be working automatically (we have integration test coverage of this that's passing). In fact, you shouldn't even need to pass the `project_id`.
