### ISSUE TITLE
opentelemetry-exporter-gcp-trace issue with dependency pinning of google-cloud-trace

### ISSUE THREAD

**Issue by frehov** [GoogleCloudPlatform/opentelemetry-operations-python#164]
It seems this package is expecting the following google-cloud-trace versioning `>=0.24.0, <1.0.0`

We're currently in the process of moving away from OpenCensus tracing as it's no longer the recommended library for tracing.
But we're hitting a wall in dependency resolution as we're trying to update to google-cloud-core 2.0.0.

the google-cloud-trace python package reached GA with release 1.1.0 as defined in the [changelog](https://googleapis.dev/python/cloudtrace/latest/changelog.html) and the latest release is currently at 1.3.2

Our main issue is that we're trying to update google-cloud-core to version 2.0.0 and are running into dependency resolution issues, due to an older version of google-cloud-trace being pinned. Version 1.3.1 of google-cloud-trace updated the dependencies to work with version 2.x of google-cloud-core and google-auth

**Comment by aabmass** [comment]
Originally we used this older version to support python 3.4. It should be possible to upgrade this dependency now

**Comment by aabmass** [comment]
> We're currently in the process of moving away from OpenCensus tracing as it's no longer the recommended library for tracing.
> But we're hitting a wall in dependency resolution as we're trying to update to google-cloud-core 2.0.0.

`opencensus-ext-stackdriver` has a similar dependency constraint of [`google-cloud-trace >= 0.20.0, < 1.0.0`](https://github.com/census-instrumentation/opencensus-python/blob/5aba7bcc720b63d6349b10bc4696702da0aed3f6/contrib/opencensus-ext-stackdriver/setup.py#L41). Is this issue actually related to moving away from OpenCensus then? I'm trying to understand if this will effect many users migrating from OpenCensus.

**Comment by frehov** [comment]
@aabmass it must've slipped my mind to open an issue on the `opencensus-ext-stackdriver` about this.

What I can say is that, anyone on google-cloud-core 2.x will not be able to implement tracing unless either library is bumped or relaxed a bit in their dependency management.

The story is that we have have dependabot running as dependency maintainer, and all our builds timed out when we got the update to `google-cloud-core` 2.0.0. On debugging why this happened, we identified the opencensus extension as the culprit for holding back the update because it was pinning an older version of `google-cloud-trace`. We then had a look at the tracing pages again, and found that they had been updated and were referring to opentelemetry as the preferred library for tracing, and a previous upgrade that disconnected `opencensus-ext-stackdriver` from the rest of opencesus version with a comment citing low activity for the reason for the disonnect. We took this as a sign that we should move away from opencensus.

I've opened the corresponding issue on opencensus now regardig the `opencensus-ext-stackdriver` library now.
https://github.com/census-instrumentation/opencensus-python/issues/1073

**Comment by aabmass** [comment]
@frehov apologies for not getting back to you earlier. Do both census-instrumentation/opencensus-python#1073 and this issue need to be resolved to fix your problem?

**Comment by miguelamavel** [comment]
we have a similar issue where we're trying to upgrade to `google-cloud-core` to version 2.0.0, in our case because of some new features in `google-cloud-storage`, and the dependency to `opentelemetry-exporter-gcp-trace` and subsequent `google-cloud-trace<1.0.0,>=0.24.0` dependency is not allowing us to make the update

**Comment by aabmass** [comment]
I'll be working on this issue next week

**Comment by frehov** [comment]
sorry for not getting back to you @aabmass, but I've been moved to a different project at my employer, and we're currently not using google cloud platform.
However, the team I was on, still uses it and would like to see these updates :)
