### ISSUE TITLE
decorator

### ISSUE THREAD

**Issue by amor71** [GoogleCloudPlatform/opentelemetry-operations-python#166]
Hello to the team,

I created a @trace decorator, which helps me trace flows in my (multi-processing) application. I was thinking it might be helpful for others. Does it already exist? is there a reason why not to have such in place? I could create a pull request if relevant. Thank you,

Amor71

**Comment by punya** [comment]
Hi @amor71. This repository is for OTel concerns that are specific to GCP, whereas your question seems broader (relevant to any Python program that uses tracing). I would suggest creating an issue in https://github.com/open-telemetry/opentelemetry-python .

**Comment by amor71** [comment]
I know. This is a specific decorator for GCP & OTel using Python.

**Comment by aabmass** [comment]
@amor71 do you mind sharing more details? My first reaction is same as @punya's that this could probably be done for a wider audience within the OTel Python upstream.
