### ISSUE TITLE
x-cloud-trace-context pattern was changed by google when setup gRPC http2.0 on Cloud RUN

### ISSUE THREAD

**Issue by paralelocslucasmagalhaes** [GoogleCloudPlatform/opentelemetry-operations-python#167]
Hi guys.. I tested the Cloud Trace Propagator on Cloud Run running a gRPC service with HTTP 2.0 enabled and figure out a problem.

On my tests I notice the pattern of x-cloud-trace-context the Google's Services send was different than "trace_id/span_id;o=Flag". On my test I've received just "trace_id/span_id" without the ";o=Flag".

So.. the actual code implemented at Cloud Trace Propagator Class does "match = re.fullmatch(_TRACE_CONTEXT_HEADER_RE, header)" The re expression wasn't fullfiled and return None. 

I have a suspicion that the change could be part of HTTP2.0 setup, cause others "REST Service" running on HTTP1.0 the x-cloud-trace-context pattern is the way we expected.

_Originally posted by @paralelocslucasmagalhaes in https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/109#issuecomment-945137050_

**Comment by punya** [comment]
@paralelocslucasmagalhaes, is this problem still relevant to you?

**Comment by kamalmarhubi** [comment]
It seems clear that there should be agreement across Google's libraries. I think the single character code change + related tests is the correct thing to do here?

**Comment by kamalmarhubi** [comment]
@punya @aabmass could you review and merge #181 then make a release? The propagator is basically broken without that change. This lost a team member at least several hours investigating why transforming load balancer logs into otel spans wasn't working.
