### ISSUE TITLE
Label `db.statement` got Truncate

### ISSUE THREAD

**Issue by lucemia** [GoogleCloudPlatform/opentelemetry-operations-python#171]
![screenshot](https://user-images.githubusercontent.com/432851/147490343-66f08e18-e95e-4003-bc2a-1d9f66c73e9d.png)

The `db.statement` label was truncated in Cloud Trace Console. Make the value useless. 

It looks like the cloud trace exporter truncated the label value to 256 character.

https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/ee23dfa616300d2762c3c974f3e2881f0a206d0b/opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py#L440-L445

https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/ee23dfa616300d2762c3c974f3e2881f0a206d0b/opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py#L479-L492

However, the [document](https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#TraceSpan.FIELDS.labels) said the limitation should be 16KB for Label values.

> Collection of labels associated with the span. Label keys must be less than 128 bytes. Label values must be less than 16 kilobytes (10MB for /stacktrace values).

Is there a way to send db.statement value without truncated?
(I used `opentelemetry-instrumentation-pymysql`)

**Comment by aabmass** [comment]
Thanks for the report, not sure why it's truncating at 256. I'll take a look

**Comment by aabmass** [comment]
I found out why it was coded to truncated at 256. The [quota page](https://cloud.google.com/trace/docs/quotas) has

> 

Size of value per label/attribute | 256 bytes
-- | --
