### ISSUE TITLE
gcp cloud trace and OTEL ResourceAttributes not working

### ISSUE THREAD

**Issue by raphaelauv** [GoogleCloudPlatform/opentelemetry-operations-python#172]
I can't find the service.name in the filters of the gcp cloud trace UI

I gave a full example there https://github.com/GoogleCloudPlatform/python-docs-samples/issues/7300

How can I filter by OTEL service.name in cloud trace ?

**Comment by aabmass** [comment]
@raphaelauv I think there are two separate issues here.

The `service.name` attribute isn't sent by default, you will need to allowlist it with this regex option: https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/ee23dfa616300d2762c3c974f3e2881f0a206d0b/opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py#L101-L102

So something like `r"service\.name"` or a more permissive regex will cause it to be added to a span label. Note this is currently unreleased, but expect a release soon.

The second issue is filtering in the UI. As you found out, the "Service" option in the filter bar is not what you want. Once the label is being sent, you can use the filter syntax you probably already saw in the docs [here](https://cloud.google.com/trace/docs/trace-filters#filter_syntax).

**Comment by aabmass** [comment]
Just released version 1.1.0 with the `resource_regex` parameter. Closing for now but let me know if you have any issues.

**Comment by raphaelauv** [comment]
in GO it's automatically manage : https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/119/files

could we add this feature to python ? @aabmass
