### ISSUE TITLE
Any chance of a version that builds against non alpha opentelemetry?

### ISSUE THREAD

**Issue by andaag** [GoogleCloudPlatform/opentelemetry-operations-python#191]
Hi

I'm trying to get in opentelemetry, the gcp propogator & exporter and the opentelemetry-instrumentation package... that's a bit of a nightmare as they all build against specific beta versions of each other.

I see opentelemetry-exporter-gcp-monitoring==1.3.0a1 depends on opentelemetry-sdk==1.10a0, any chance you can build this against 1.11.*? That would make version resolving but still getting bugfixes a lot easier.

**Comment by aabmass** [comment]
@andaag thanks for opening the issue. It's a known problem, looks like https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/190 addresses this. I think OTel metrics is about stable enough that we could take this on in the next few weeks.

**Comment by aabmass** [comment]
I'm working on this now and should have a PR up soon. There are two open PRs attempting this (https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/190, https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/187) but they are outdated or tests failing. Thanks for bearing with me.

**Comment by aabmass** [comment]
Main branch is now working with 1.x OTel. I will do a few more changes and then hopefully cut a release soon.
