### ISSUE TITLE
Add support for python 3.11

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/opentelemetry-operations-python#206]
Until https://github.com/googleapis/proto-plus-python/issues/326 is fixed, client libraries don't properly support 3.11. Revert https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/205

**Comment by aabmass** [comment]
Still blocked

**Comment by Lawouach** [comment]
Hello. Is this still opened? Just wondering as I'm heavily relying on Python 3.11 in GCP.

**Comment by aabmass** [comment]
The linked issue is fixed so it probably works now. I don't remember how I found out it was broken, and can't tell from my old PRs. Let me try adding 3.11 back and see if things pass.
