### ISSUE TITLE
Set entrypoint for metrics exporter for use with auto instrumentation

### ISSUE THREAD

**Issue by anuraaga** [GoogleCloudPlatform/opentelemetry-operations-python#266]
Currently, the entrypoint for trace exporter is set and can be used with auto instrumentation

https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/opentelemetry-exporter-gcp-trace/setup.cfg#L41

The same is not done for metrics exporter

https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/opentelemetry-exporter-gcp-monitoring/setup.cfg#L36

OpenTelemetry does have support for it for metrics too

https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py#L268

Would it be OK to define the entrypoint `gcp_metrics` for the metrics exporter to be able to use it with auto instrumentation?

**Comment by dashpole** [comment]
This would be really useful!  @aabmass will take this on, and try to get it in the next release
