### ISSUE TITLE
GCP resource detector throws an exception if not run on GCP

### ISSUE THREAD

**Issue by Tasty213** [GoogleCloudPlatform/opentelemetry-operations-python#276]
Hi,

The GCP resource detector throws an exception when it's not being run on GCP this is expected but should probably be suppressed if the raise on error attribute is set to false. The exact use case for this is being able to run a local dev environment or a CI pipeline on a non google cloud machine but without needing to have an "if dev mode switch".

**Comment by Tasty213** [comment]
Minimum example

```
from opentelemetry.resourcedetector.gcp_resource_detector import GoogleCloudResourceDetector, NoGoogleResourcesFound

try:
    detector = GoogleCloudResourceDetector(raise_on_error=False)
    resources = detector.detect()
except NoGoogleResourcesFound:
    print("This shouldn't be hit")
    
```

**Comment by aabmass** [comment]
Thanks for reporting, this sounds like a bug. If you'd like to contribute a fix, PRs are welcome. Otherwise I can try to fix it for the next release
