### ISSUE TITLE
Setting the "ERROR" status doesn't show correctly in Google Cloud Trace

### ISSUE THREAD

**Issue by multani** [GoogleCloudPlatform/opentelemetry-operations-python#303]
When an error occured and after I set [span status to `ERROR`](https://opentelemetry.io/docs/concepts/signals/traces/#span-status), the span doesn't show up as error in Google Cloud Trace.

Consider the following example:

```python
#!/usr/bin/env python3

from opentelemetry import trace
from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.trace import Status, StatusCode


def setup():
    exporter = CloudTraceSpanExporter()
    # exporter = OTLPSpanExporter(endpoint="127.0.0.1:4317", insecure=True)
    print(f"Using tracing exporter {exporter}")

    processor = BatchSpanProcessor(exporter)

    resource = Resource(attributes={SERVICE_NAME: "test"})
    tracer_provider = TracerProvider(resource=resource)
    tracer_provider.add_span_processor(processor)

    trace.set_tracer_provider(tracer_provider)


def main():
    setup()

    tracer = trace.get_tracer(__name__)
    with tracer.start_as_current_span("first") as span:
        try:
            raise Exception("oh no")
        except Exception as exc:
            span.record_exception(exc)
            span.set_status(Status(StatusCode.ERROR))
            # span.set_attribute("http.status_code", 500)


if __name__ == "__main__":
    main()
```

It shows up like this in Google Cloud Trace:
![Screenshot from 2023-12-07 22-16-01](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/assets/65311/d0564756-589c-4936-afc5-f31c5aec3992)
![Screenshot from 2023-12-07 22-16-10](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/assets/65311/510aa3fe-0b13-4aed-b346-b20645880c19)

If I switch the exporter from `CloudTraceSpanExporter` to the `OTLPSpanExporter` (towards Jaeger), it shows up correctly in Jaeger:

![image](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/assets/65311/fe196b1d-9247-4874-bce2-6fe4c045dd87)

Setting the span attribute `http.status_code` to `500` shows up correctly though, but this doesn't use the "official" [status](https://opentelemetry.io/docs/concepts/signals/traces/#span-status) mechanism from OpenTelemetry:

![image](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/assets/65311/8ee409a3-d5e6-4a0a-97c9-5ccc93a81470)

**Comment by aabmass** [comment]
@multani this was also reported in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/730

Unfortunately we can't do anything in the exporter to fix it. Please follow along on that bug.
