### ISSUE TITLE
Why Cloud Functions appear as 'generic_task' in `monitored_resource` in metrics.

### ISSUE THREAD

**Issue by damjad** [GoogleCloudPlatform/opentelemetry-operations-python#314]
Hello, 

I am pretty new to OpenTelemetry. 

I have used the packages in this repo for exporting metrics directly to Stack Driver (GCP Monitoring Service). 

However, I see that when I use a GCF v2, it appears to be a 'generic_task' in metrics. I tried several things and nothing worked. 

In the end, I dug into the code and found out that the logic was not there to handle GCF. The file is this one 
https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/main/opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector/_mapping.py#L145.

My question here is that is it intentionally not implemented or is it going to be available in the future?

**Comment by dashpole** [comment]
It is intentionally mapped to generic task.  The monitored resource for cloud function is not writeable for custom metrics.  Feel free to ask questions in our slack channel, #otel-gcp as well: https://app.slack.com/client/T08PSQ7BQ/C043XTR0JHF
