### ISSUE TITLE
Resource labels dict copied repeatedly

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/opentelemetry-operations-python#44]
OpenTelemetry's `Resource.labels` property actually copies the labels dict: https://github.com/open-telemetry/opentelemetry-python/blob/8bc7786b191b4f1b1f161de983db71643bf9f51e/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L41-L43

So each access is here is copying the dict:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/a3f35dab9bf9e90fde5ab6acd274f6ec7b2567b4/opentelemetry-exporter-cloud-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py#L103-L116

If the goal of `Resource` doing this is to achieve immutability, maybe it can be updated upstream to use a FrozenDict/ImmutableDict library?

**Comment by aabmass** [comment]
@AndrewAXue can you take this?

**Comment by AndrewAXue** [comment]
PR up here PTAL https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/45
