### ISSUE TITLE
Add Cloud Trace propagator

### ISSUE THREAD

**Issue by kintel** [GoogleCloudPlatform/opentelemetry-operations-python#5]
The OpenTelemetry SDK ships with propagators for Zipkin and Jaeger. OpenCensus also ships with a propagator for Cloud Trace (x-cloud-trace-context): https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/propagation/google_cloud_format.py

We should add a Cloud Trace propagator to this exporter.

-> this could offer customers the possibility of being compatible with existing services that are not yet instrumented using OpenTelemetry by e.g. being able to extract either header format and inject both headers formats.

**Comment by AndrewAXue** [comment]
Addressed in https://github.com/open-telemetry/opentelemetry-python/pull/819
