### ISSUE TITLE
CloudTraceExporter drops all spans if even one is malformed

### ISSUE THREAD

**Issue by AndrewAXue** [GoogleCloudPlatform/opentelemetry-operations-python#54]
If even one of the spans passed in a batch to CloudTraceExporter is malformed, when it attempts to export these, the Cloud Trace backend will complain and as a result none of the spans in the batch will be exported. A proposed solution is a divide and conquer algorithm that, given an array of spans (possibly a subarray) will attempt to export the left and right halves of the array. If it succeeds, continue, otherwise if it fails recurse on the half that failed. 

def exportDivide(arr_of_spans):
    left = arr_of_spans[:len(arr_of_spans)/2], right = arr_of_spans[len(arr_of_spans)/2:]
    try left export
    if left export failed: exportDivide(left)
    try right export
    if right export failed: exportDivide(right)

This will require O(klogn) calls the backend where k is the number of malformed spans and n is the number of spans. One issue with this approach is that if k is large, say k == n, then we would do O(nlogn) calls to the backend which is far too slow. The size of the stack also shouldn't be an issue since there would be log(n) recursive calls to the function.

**Comment by aabmass** [comment]
Curious what you mean by malformed?

**Comment by AndrewAXue** [comment]
To clarify, a malformed span is one that cannot be exported for various reasons like incorrect project_id, invalid trace_id, etc.

**Comment by AndrewAXue** [comment]
Resolved with further exploration https://docs.google.com/document/d/1G0fq0GbULOimESoBGd7gVHYDl-RlRd7QNV4jjrAiz4k/edit
