### ISSUE TITLE
Use protobuf objects instead of dicts where possible

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/opentelemetry-operations-python#56]
Several places we are using dictionaries and then either letting the library convert or doing `SomeProto(**d)`. It would be better to use protos directly

Waiting for #64

**Comment by tonyshi1998** [comment]
Hey! Is this still needed? I'd love to work on it if it is. 

Also, is there a way I can message you @aabmass for a few quick questions? Thanks!

**Comment by aabmass** [comment]
I fixed this for trace in #170. Still needs to be fixed for the Cloud Monitoring exporter

https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/93cac30c8cf71777a26b1eb4203cd7b1b1472941/opentelemetry-exporter-gcp-monitoring/src/opentelemetry/exporter/cloud_monitoring/__init__.py

Thanks for taking this on, assigned to you!

**Comment by aabmass** [comment]
You can DM me on CNCF Slack https://slack.cncf.io/ 😃
