### ISSUE TITLE
Add upper bounds for google-cloud-monitoring and google-cloud-trace

### ISSUE THREAD

**Issue by busunkim96** [GoogleCloudPlatform/opentelemetry-operations-python#69]
Hi,

I'm on the Cloud Client Libraries team. Just wanted to give you folks a heads up that we're in the process of making major version bumps to the Python libraries with breaking changes. I'm about to cut a release for `google-cloud-trace` and monitoring will follow in a week or two.

Please pin the dependencies on these libraries to less than the next major to avoid breaking users.

https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/0691ca909cdf20808271064967f4466394122ee0/opentelemetry-exporter-google-cloud/setup.cfg#L28-L30

```py
google-cloud-monitoring<2.0.0
google-cloud-trace>=0.24.0, <1.0.0
```
Thanks!

**Comment by aabmass** [comment]
Thanks for the heads up!
