### ISSUE TITLE
ModuleNotFoundError: No module named 'google.cloud.trace_v2.proto'

### ISSUE THREAD

**Issue by dgildeh** [GoogleCloudPlatform/opentelemetry-operations-python#71]
It looks like a dependent module, google-cloud-trace, released a new major version yesterday, with breaking package changes, breaking our deployment and bringing down our entire service: https://github.com/googleapis/python-trace/blob/master/CHANGELOG.md

Please can you update this module to use the latest release of google-cloud-trace, or lock the version that works with the current module (0.24.0). If you update the code to work with the new module, please lock the version that works so this doesn't happen again (or only support minor version updates).

I fixed it by adding this line to the end of my requirements.txt file to override the automatically installed version installed when adding this module:

google-cloud-trace==0.24.0

**Comment by aabmass** [comment]
Fixed in #73, which was released in 0.13b0
