### ISSUE TITLE
g.co/agent defaulting to opencensus	

### ISSUE THREAD

**Issue by aravinsiva** [GoogleCloudPlatform/opentelemetry-operations-python#9]
When running opentelemetry cloud-exporter on GKE a default agent is set to opencensus when opentelemetry is the framework being used.

Potentially may be a default collector set up by GCP. 

Opentelemetry Version: v0.9.0
Cloud Exporter Version: 0.10.dev0

**Comment by aravinsiva** [comment]
# Experimented With Issue #

This was experimented using the Cloud Trace QuickStart Documentation found here:
https://cloud.google.com/trace/docs/quickstart

## What was done: ##
All telemetry libraries were removed to see if spans were still created. As well as to see if the g.co/agent tag was still set to opencensus. (The issue originally came up as 

## Outcome: ##
It was noticed that even with no telemetry library that spans were still being generated and the g.co/agent was still being set to opencensus. As a result after discussions with Chris and Andrew it was determined that the likely reason for this was the fact that GKE has a default opencensus collector that accepts all requests and exports the data.

**Comment by aabmass** [comment]
Sounds like this issue can be closed. `g.co/agent` is written correctly [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/bb517e105855ed715618f9411065de8f6d02ecd7/opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py#L415)
