### ISSUE TITLE
0.17b0? / PyPI release

### ISSUE THREAD

**Issue by twoodwark** [GoogleCloudPlatform/opentelemetry-operations-python#97]
Hi there, I see https://pypi.org/project/opentelemetry-exporter-google-cloud/ is still on 0.16b1.  Is there any chance of a new release? 

I'd find it really useful to have 0.17b0 there.  

I'm intending to add a conda-forge feedstock for this package, but other packages like https://anaconda.org/conda-forge/opentelemetry-api are already at opentelemetry version 0.17b0,  skipping 0.16b1.

**Comment by aabmass** [comment]
Thanks for reporting, cutting a new release now
